### ISSUE TITLE
Custom formats not added to other textareas

### ISSUE THREAD

**Issue by blogjunkie** [justcoded/just-tinymce-custom-styles#6]
Not sure if this is a bug or by design, but I realized that the custom formats are not added to textareas in Beaver Builder and Advanced Custom Fields. Other TinyMCE plugins I've tried e.g. [TinyMCE Custom Styles](https://wordpress.org/plugins/tinymce-custom-styles/) do so.

If this is not a bug, is there a filter I can use to enable the custom formats on other textareas too?

Thank you

**Comment by aprokopenko** [comment]
Hi,

Thank you for interesting in our plugin.
You're the first who reported such an issue. We will investigate it and return to you with a solution. 

We used standard editor hook to update tinyMCE init options. We are not using Beaver Builder, but ACF support is a must nowadays and we will search for a new hooks to make it works too.

**Comment by aprokopenko** [comment]
Hi,

I checked the reported issue. 

It works fine with ACF. You should use "Full" toolbar option to see the Formats dropdown:

http://prntscr.com/g5g9h4

http://prntscr.com/g5g8ld

If it doesn't work for you the problem can be with some conflicts with other plugins.
