### ISSUE TITLE
User does not see the styles

### ISSUE THREAD

**Issue by ChrisDorna** [justcoded/just-tinymce-custom-styles#9]
I am using just-tinymce-custom styles and I see the styles in the editor but they are not vissible to the visitors of my site?

**Comment by aprokopenko** [comment]
Hi Chris,

Yes this is correct. This plugin is used with custom theme, which has special css classes to format something. But standard WP editor doesn't allow you to insert these classes. 
This plugin gives you the ability to set custom css classes directly inside editor. When you add new formats, styles are required to visualize the some element has some styles, but they don't shared to the frontend
